version: "2"
services:
    www:
        build: .
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/devops/
        networks:
            - default
volumes:
    persistent: