version: "2"
services:
    www:
        build: .
        ports:
            - "8001:80"
        volumes:
            - ./src:/var/www/devops/src
            - ./tests:/var/www/devops/tests
            - ./console:/var/www/devops/console
            - ./config:/var/www/devops/config
        networks:
            - default
volumes:
    persistent:
